import { Link } from 'react-router-dom';

const H2 = 'mt-8 font-display text-lg font-semibold text-ink';
const P = 'mt-3 text-sm leading-relaxed text-slate-600';
const UL = 'mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed text-slate-600';

// Standalone layout on purpose -- AuthLayout's narrow card + looping video
// background is built for a short login form, not a long-form document.
// [CONTACT EMAIL] is a placeholder: confirm the real public support/privacy
// contact address before this goes live -- see the note left for the user
// in chat.
export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-canvas px-4 py-12">
      <div className="mx-auto max-w-2xl rounded-2xl bg-white p-8 shadow-card sm:p-10">
        <Link to="/login" className="text-sm text-teal-600 hover:underline">
          ← Back to Tyrotec
        </Link>

        <h1 className="mt-4 font-display text-2xl font-semibold text-ink">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">
          Last updated: {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>

        <p className={P}>
          This policy explains what personal information Tyrotec ("Tyrotec", "we", "us") collects through this
          customer portal and WhatsApp ordering service, why we collect it, who we share it with, and the rights
          you have over it. It's written to align with South Africa's Protection of Personal Information Act, 2013
          ("POPIA"). If you're outside South Africa, similar protections generally apply under your local law.
        </p>

        <h2 className={H2}>1. Who this applies to</h2>
        <p className={P}>
          This policy covers customers who register for or use the Tyrotec portal or its WhatsApp ordering
          service, and staff (sales representatives and administrators) who use the portal to manage products,
          quotes, orders, and payments on our behalf.
        </p>

        <h2 className={H2}>2. Information we collect</h2>
        <ul className={UL}>
          <li>
            <strong>Account information:</strong> name or company name, email address, password (stored in hashed
            form by our authentication provider, never in plain text), role, and account status.
          </li>
          <li>
            <strong>Phone number (optional):</strong> if you link a phone number, we use it to recognize you when
            you message us on WhatsApp so you can browse products, build quotes, and place orders there using the
            same account.
          </li>
          <li>
            <strong>Transaction information:</strong> the products, quotes, orders, and payment details (method,
            reference number, amount) you submit through the portal or WhatsApp. We do not process card payments
            ourselves or store full banking details. Payments are bank transfers/EFT that our staff verify
            manually against a bank statement.
          </li>
          <li>
            <strong>Google account information:</strong> if you sign in with Google, we receive your name and email
            address from Google to create or match your account.
          </li>
          <li>
            <strong>WhatsApp messages:</strong> the content of messages you send us on WhatsApp while using the
            ordering service, so we can respond to and process your requests.
          </li>
          <li>
            <strong>Staff-uploaded documents:</strong> when staff use the product-import tool, files they upload
            (supplier receipts or spreadsheets) are processed to extract product information. This is an internal
            staff tool. Customers do not upload documents through it.
          </li>
          <li>
            <strong>Technical information:</strong> basic access logs generated by our hosting providers as a
            normal part of running the service (e.g. request timestamps, error logs). We do not use third-party
            advertising or tracking cookies.
          </li>
        </ul>

        <h2 className={H2}>3. Why we process this information</h2>
        <p className={P}>We process your information to:</p>
        <ul className={UL}>
          <li>Create and manage your account, and verify who you are when you sign in;</li>
          <li>Let you browse our catalog and build, submit, and track quotes and orders;</li>
          <li>Let you order via WhatsApp and recognize you across both channels;</li>
          <li>Review and confirm the payments you submit;</li>
          <li>Send you notifications about your quotes, orders, and payments (in-app and by email);</li>
          <li>Keep our product catalog accurate and stock levels up to date;</li>
          <li>Maintain the security of the portal and investigate misuse.</li>
        </ul>
        <p className={P}>
          Our basis for processing is that it's necessary to perform our contract with you (fulfilling orders you
          place), your consent (e.g. linking a phone number for WhatsApp), or our legitimate business interests in
          operating and securing the service.
        </p>

        <h2 className={H2}>4. Who we share information with</h2>
        <p className={P}>
          We don't sell your personal information. We share it only with the service providers that help us run
          Tyrotec, each acting on our instructions:
        </p>
        <ul className={UL}>
          <li>
            <strong>Supabase</strong>: our database, authentication, and file storage provider.
          </li>
          <li>
            <strong>Render</strong>: hosts our backend server.
          </li>
          <li>
            <strong>Meta (WhatsApp Business Platform)</strong>: delivers and receives WhatsApp messages when you
            use WhatsApp ordering.
          </li>
          <li>
            <strong>Google</strong>: provides Google Sign-In (if you use it) and the AI model used by staff's
            internal product-import tool.
          </li>
          <li>
            Our email provider: sends account and order notification emails.
          </li>
        </ul>
        <p className={P}>
          We may also disclose information where required by law, or to protect the rights, property, or safety of
          Tyrotec, our customers, or others.
        </p>

        <h2 className={H2}>5. How long we keep it</h2>
        <p className={P}>
          We retain account and transaction information for as long as your account is active and afterwards for as
          long as needed to meet legal, accounting, or dispute-resolution requirements. You can ask us to delete
          your account information subject to those requirements (see Section 7).
        </p>

        <h2 className={H2}>6. Security</h2>
        <p className={P}>
          We use industry-standard measures to protect your information, including encrypted connections (HTTPS),
          hashed passwords, role-based access controls so staff only see what their role requires, and
          database-level access restrictions. No system is completely secure, but we work to keep your information
          protected and will notify you if we become aware of a breach affecting you, as required by law.
        </p>

        <h2 className={H2}>7. Your rights</h2>
        <p className={P}>Subject to applicable law, you have the right to:</p>
        <ul className={UL}>
          <li>Access the personal information we hold about you;</li>
          <li>Ask us to correct information that's inaccurate or incomplete;</li>
          <li>Ask us to delete your information, subject to our legal/accounting obligations;</li>
          <li>Object to certain processing, or withdraw consent (e.g. unlink your phone number);</li>
          <li>Lodge a complaint with South Africa's Information Regulator if you believe we've mishandled your information.</li>
        </ul>
        <p className={P}>To exercise any of these rights, contact us using the details in Section 10.</p>

        <h2 className={H2}>8. Cookies and local storage</h2>
        <p className={P}>
          The portal stores a login session token in your browser's local storage so you stay signed in between
          visits. We don't use third-party advertising or analytics tracking cookies.
        </p>

        <h2 className={H2}>9. Children's privacy</h2>
        <p className={P}>
          Tyrotec is a business-to-business service and isn't directed at or intended for use by children.
        </p>

        <h2 className={H2}>10. Contact us</h2>
        <p className={P}>
          For any questions about this policy or your personal information, contact us at{' '}
          <span className="font-medium text-ink">privacy@tyrotec.co.za</span>.
        </p>

        <h2 className={H2}>11. Changes to this policy</h2>
        <p className={P}>
          We may update this policy from time to time. We'll update the "Last updated" date above when we do, and
          for significant changes we'll take reasonable steps to let you know.
        </p>
      </div>
    </div>
  );
}
